# Generated by Django 3.1 on 2020-08-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(default='0')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('RAM', models.CharField(max_length=50)),
                ('HardDisk', models.CharField(default='', max_length=50)),
                ('SSD', models.CharField(max_length=50)),
                ('Battery', models.CharField(max_length=50)),
                ('Charger', models.CharField(max_length=50)),
                ('Processor_Model', models.CharField(max_length=50)),
                ('MacAddress', models.CharField(max_length=50)),
                ('date1', models.DateField()),
                ('time1', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(default='0')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('RAM', models.CharField(max_length=50)),
                ('HardDisk', models.CharField(default='', max_length=50)),
                ('SSD', models.CharField(max_length=50)),
                ('Battery', models.CharField(max_length=50)),
                ('Processor_Model', models.CharField(max_length=50)),
                ('Charger', models.CharField(max_length=50)),
                ('MacAddress', models.CharField(max_length=50)),
                ('date1', models.DateField()),
                ('time1', models.TimeField()),
            ],
        ),
    ]
